version: "3.9"
services:
  backend:
    image: kupalovmuhammadjo/turniket:latest
    network_mode: host
    restart: unless-stopped
    privileged: true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - "dialout"
      - "tty"
    environment:
      HTTP_ADDR: ":8088"
      VALIDATOR_URL: "${VALIDATOR_URL:-http://ice-city-kassa.knative-fn.u-code.io}"
      VALIDATOR_TOKEN: "${VALIDATOR_TOKEN:-}"
      NFC_SOURCE: "${NFC_SOURCE:-none}"
      PSEUDO_ALLOW_ALL: "${PSEUDO_ALLOW_ALL:-false}"
      GATE_SERIAL_PORT: "${GATE_SERIAL_PORT:-}"
      GATE_OPEN_TIMEOUT_S: "${GATE_OPEN_TIMEOUT_S:-2}"
      MAC_ADDRESS: "${MAC_ADDRESS:-}"

  kiosk:
    build:
      context: ./kiosk
      dockerfile: Dockerfile
    image: kupalovmuhammadjo/turniket-kiosk:latest
    container_name: turniket-kiosk
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - backend
    environment:
      LAUNCH_URL: "http://localhost:8088/frontend/index.html"
      CHROMIUM_FLAGS: "--kiosk --no-sandbox --noerrdialogs --disable-infobars --check-for-update-interval=31536000 --start-fullscreen --no-first-run --disable-features=TranslateUI --disable-gpu --disable-dev-shm-usage --user-data-dir=/home/kiosk/.config/chromium --disk-cache-dir=/tmp/chromium-cache"
      DISPLAY: ":0"
    network_mode: host
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup --label-enable
