version: "3.9"
services:
  backend:
    image: kupalovmuhammadjo/turniket:latest
    network_mode: host
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - "dialout"
      - "tty"
    environment:
      HTTP_ADDR: ":8088"
      VALIDATOR_URL: "${VALIDATOR_URL:-http://ice-city-kassa.knative-fn.u-code.io}"
      VALIDATOR_TOKEN: "${VALIDATOR_TOKEN:-}"
      NFC_SOURCE: "${NFC_SOURCE:-none}"
      PSEUDO_ALLOW_ALL: "${PSEUDO_ALLOW_ALL:-false}"
      GATE_SERIAL_PORT: "${GATE_SERIAL_PORT:-}"
      MAC_ADDRESS: "${MAC_ADDRESS:-}"

  kiosk:
    image: kupalovmuhammadjo/turniket-kiosk:latest
    container_name: turniket-kiosk
    depends_on:
      - backend
    environment:
      LAUNCH_URL: http://localhost:8088/frontend/index.html
      CHROMIUM_FLAGS: "--kiosk --no-sandbox --noerrdialogs --disable-infobars --check-for-update-interval=31536000 --start-fullscreen --no-first-run --fast --fast-start --disable-features=TranslateUI --disk-cache-dir=/dev/null"
      DISPLAY: "${DISPLAY:-:0}"
    network_mode: host
    restart: unless-stopped
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - "${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:ro"
